name: Release mMojo

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Release mMojo
        uses: krn-sebastiaan/actions/release@main
        with:
          krn-core-repository-url: 'https://krn-sebastiaan.github.io/mmojo-repositories/demo-repositories.xml'
          build-arguments: '-Dlog_level=debug'
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
